version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  mqtt2prometheus:
    image: ghcr.io/hikhvar/mqtt2prometheus
    ports:
      - "9641:9641"
    volumes:
      - ./mqtt2prometheus.config.yml:/config.yaml
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image:  grafana/grafana-oss
    ports:
      - "3000:3000"

volumes:
  prometheus.yml:
  mosquitto.conf:
  mqtt2prometheus.config.yml:
